"""add retrieval steps table

Revision ID: 05a8db72ae6a
Revises: 884eb218c331
Create Date: 2026-09-10 22:35:52.152740

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "05a8db72ae6a"
down_revision: str | None = "884eb218c331"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retrieval_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Uuid(), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=True),
        sa.Column("retrieved_tokens", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["traces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("retrieval_steps")
    # ### end Alembic commands ###
