"""add langfuse keys to projects

Revision ID: 884eb218c331
Revises: b4135a84571a
Create Date: 2026-09-10 22:02:07.360839

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '884eb218c331'
down_revision: str | None = 'b4135a84571a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('langfuse_public_key', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('langfuse_secret_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'langfuse_secret_key')
    op.drop_column('projects', 'langfuse_public_key')
    # ### end Alembic commands ###
