"""add optimization recommendations table

Revision ID: 9f3a2c7d5e21
Revises: 05a8db72ae6a
Create Date: 2026-09-10 22:40:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9f3a2c7d5e21"
down_revision: str | None = "05a8db72ae6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "optimization_recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("workflow", sa.String(), nullable=True),
        sa.Column("environment_id", sa.Uuid(), nullable=True),
        sa.Column("rule_name", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("current_config", sa.JSON(), nullable=False),
        sa.Column("proposed_config", sa.JSON(), nullable=False),
        sa.Column("estimated_cost_impact", sa.Text(), nullable=False),
        sa.Column("required_experiment", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("optimization_recommendations")
    # ### end Alembic commands ###
